name: Get Website Preview
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          url: https://cloudirector.github.io
          mode: page
      - uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: ${{ github.workspace }}/*.png
